version: '3.8'

services:
  loki:
    image: grafana/loki:2.7.3
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - ./loki-data/wal:/loki/wal
      - ./loki-data/index:/loki/index
      - ./loki-data/cache:/loki/cache
      - ./loki-data/chunks:/loki/chunks
    networks:
      - loki-network

  promtail:
    build:
      context: .
      dockerfile: Dockerfile.promtail
    volumes:
      - ./promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log/flask:/var/log/flask
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki-network




  grafana:
    image: grafana/grafana:8.4.3
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - loki-network

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/%2F
    volumes:
      - .:/app
      - ./flask_logs:/var/log/flask
    depends_on:
      - rabbitmq
      - loki
    command: /bin/sh -c "mkdir -p /var/log/flask && python run.py"
    networks:
      - loki-network

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    networks:
      - loki-network

volumes:
  grafana-data:

networks:
  loki-network:
