server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: todo_web_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: todo_web
          __path__: /var/log/app.log
    pipeline_stages:
      - json:
          expressions:
            level: level
            msg: message
            time: time
            stream: stream

